version: 0.1

phases:
  build:
    commands:
      - mvn package
artifacts:
  files:
    - examples/target/examples.zip
    - website/target/ROOT.war
    - website/scripts/*.sh
    - appspec.yml
  discard-paths: yes